services:
  webapi:
    build: .
    ports:
      - "8080:8080"
      - "8081:8080"
      - "8082:80"
    networks:
      - net1
    depends_on:
      - db
  db: 
    image: mcr.microsoft.com/mssql/server:2022-latest
    networks:
      - net1
    hostname: sqlserver
    volumes:
      - sqldata:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=@623541Mm
networks:
  net1:

volumes:
  sqldata: